# Generated by Django 5.0.7 on 2024-08-09 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_cliente_rename_plantas_pedido_planta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidoplanta',
            name='pedido',
        ),
        migrations.RemoveField(
            model_name='pedidoplanta',
            name='planta',
        ),
        migrations.DeleteModel(
            name='Pedido',
        ),
        migrations.DeleteModel(
            name='PedidoPlanta',
        ),
    ]
